using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FSEDataFeed
{
    public static class AircraftMakeModelStrEnum
    {
        public const string Boeing737_800 = "Boeing 737-800";
        public const string Boeing747_400 = "Boeing 747-400";
    }

    //TODO: load all of the make model details from the csv file
    public class AircraftMakeModelDetails
    {
        public static List<string> AircraftMakeModelList = new List<string>() {
            "Aermacchi - Lockheed AL-60",
            "Aero Design AC500C",
            "Aero Design AC680S",
            "Aero Vodochody L-39",
            "Aeronca Champion",
            "Agusta A109",
            "Agusta Westland AW139",
            "Airbus A320",
            "Airbus A321",
            "Airbus H145",
            "Airbus Helicopters H145",
            "Aircreation 582SL",
            "Airspeed AS-57 Ambassador",
            "Alenia C-27J Spartan",
            "Alenia C-27J Spartan (IRIS)",
            "American Champion Scout",
            "Antonov An-14",
            "Antonov AN-2",
            "Antonov An-24",
            "Antonov An-26 Curl",
            "Antonov An-28",
            "Antonov An-32",
            "ATR 42-500",
            "ATR 72-500",
            "Auster J/1 Autocrat",
            "Australia GAF N22 Nomad",
            "Aviat A-1 Husky",
            "Avro Anson MK-1",
            "BAC Jet Provost T5",
            "BAe 146-100 (Avro RJ70)",
            "BAe Jetstream 32",
            "BAe Jetstream 41",
            "Basler BT-67",
            "Beagle B 206 Basset",
            "Beechcraft 17",
            "Beechcraft 18",
            "Beechcraft 1900C",
            "Beechcraft 1900C Freighter",
            "Beechcraft 1900D",
            "Beechcraft Baron 58",
            "Beechcraft Baron 58 - tip tanks (Dreamfleet)",
            "Beechcraft Bonanza A36",
            "Beechcraft Bonanza F33",
            "Beechcraft Bonanza V35",
            "Beechcraft Debonair",
            "Beechcraft Duchess 76",
            "Beechcraft Duke B60",
            "Beechcraft King Air 200",
            "Beechcraft King Air 300",
            "Beechcraft King Air 350",
            "Beechcraft King Air C90",
            "Beechcraft Queen Air",
            "Beechcraft Queen Air 80S",
            "Beechcraft Royal Turbine Duke B60",
            "Beechcraft T-34 Mentor",
            "Beechcraft Twin Bonanza 50",
            "Bell 205A-1/UH-1C",
            "Bell 206B",
            "Bell 206L RTW N3911Z",
            "Bell 212",
            "Bell 407",
            "Bell 407 (Nemeth)",
            "Bell 412",
            "Bell 429",
            "Bell 430",
            "Bell 430 RTW N430Q",
            "Bell 47G-2",
            "Bell UH-1H Huey",
            "Bellanca 260",
            "Beriev BE-103",
            "Boeing 221A Monomail",
            "Boeing 247D",
            "Boeing 377",
            "Boeing 727-100/200",
            "Boeing 737-800",
            "Boeing 747-400",
            "Boeing B-17G",
            "Boeing Stearman",
            "Boeing Vertol CH-46D Sea Knight (BV107)",
            "Boeing Vertol CH-47 Chinook",
            "Bombardier Challenger 300",
            "Bombardier CL-415",
            "Bombardier CRJ-200ER",
            "Bombardier CRJ700-ER",
            "Bombardier Dash-8 Q400",
            "Bombardier Lear 60",
            "Bristol Britannia 300",
            "Bristol Mark 32 Superfreighter",
            "Britten Norman BN-2A Mk3-3 Trislander",
            "Britten-Norman BN-2B Islander",
            "Bucker Jungmann 131",
            "CASA CN235",
            "Cessna 152 Aerobat",
            "Cessna 162 Skycatcher",
            "Cessna 172 Skyhawk",
            "Cessna 177 Cardinal",
            "Cessna 177RG Cardinal",
            "Cessna 182 Skylane",
            "Cessna 185 Skywagon",
            "Cessna 195",
            "Cessna 206 Stationair",
            "Cessna 207 Stationair 8",
            "Cessna 208 Caravan",
            "Cessna 210 Centurion",
            "Cessna 310",
            "Cessna 337 Skymaster",
            "Cessna 340A",
            "Cessna 404 Titan",
            "Cessna 414A Chancellor",
            "Cessna 421 Golden Eagle",
            "Cessna 441 Conquest II",
            "Cessna Citation CJ1",
            "Cessna Citation II",
            "Cessna Citation X",
            "Cessna L-19/O-1 Birddog",
            "Cessna Mustang",
            "Cessna Soloy Mk1/MkII U206 Turbo",
            "Cessna T-50 Bobcat",
            "Cessna T303 Crusader",
            "Cessna/Reims F-406 Caravan II",
            "Cirrus SR20",
            "Cirrus SR22 G2",
            "Cirrus Vision SF50",
            "Columbia 400",
            "Commander 112",
            "Commander 115",
            "Consolidated C-87 Liberator Express",
            "Consolidated PBY5 Catalina",
            "Convair 340/440",
            "Convair 580",
            "Curtiss C46",
            "Curtiss Robertson Robin J-1",
            "Dassault Falcon 50",
            "Dassault Falcon 7X",
            "DeHavilland Dash 7",
            "DeHavilland Dash 8 100/200",
            "DeHavilland Dash 8 Q300",
            "DeHavilland DH 89 Dragon Rapide",
            "DeHavilland DH-82 Tiger Moth",
            "DeHavilland DH104 Dove",
            "DeHavilland DH114 Heron",
            "DeHavilland DH80A Puss Moth",
            "DeHavilland DHC-1 Chipmunk",
            "DeHavilland DHC-2 Beaver",
            "DeHavilland DHC-2 Turbo Beaver",
            "DeHavilland DHC-3 Otter",
            "DeHavilland DHC-3-T Turbo Otter",
            "DeHavilland DHC-3T Turbo Otter (Milviz)",
            "DeHavilland DHC-4 Caribou",
            "DeHavilland DHC-5 Buffalo",
            "DeHavilland DHC-6 300 Twin Otter (Aerosoft Extended)",
            "DeHavilland DHC-6 Twin Otter",
            "Diamond DA20 Katana",
            "Diamond DA40D DiamondStar",
            "Diamond DA42 Twin Star",
            "Diamond DA62",
            "Dornier 228",
            "Dornier 328",
            "Dornier Do-27 A4",
            "Dornier Do-27 B1",
            "Dornier Do-28 A/B",
            "Douglas A-26",
            "Douglas C117D",
            "Douglas DC-2",
            "Douglas DC-2 (FSX)",
            "Douglas DC-3",
            "Douglas DC-4",
            "Douglas DC-6",
            "Douglas DC-6B",
            "Douglas DC-6B (PMDG)",
            "Douglas DC-7B",
            "Douglas DC-7C",
            "Douglas DC-8 (10-40)",
            "Eclipse 500",
            "Embraer 110",
            "Embraer 120",
            "Embraer ERJ-135LR",
            "Embraer ERJ-145LR",
            "Embraer Legacy 600",
            "Embraer Phenom 100",
            "Embraer Phenom 300",
            "ERCO Ercoupe 415-C",
            "Eurocopter AS-332 Super Puma",
            "Eurocopter AS-350 Ecureuil",
            "Eurocopter AS365",
            "Eurocopter BK117",
            "Eurocopter Colibri EC 120",
            "Eurocopter EC-135",
            "Fairchild 24R",
            "Fairchild C119",
            "Fairchild C123",
            "Fairchild Metro III",
            "Fairchild PT19/26 Cornell",
            "Fokker 50",
            "Fokker F27-500 Friendship",
            "Ford Tri-Motor",
            "Found Bush Hawk",
            "Gippsland GA8 Airvan",
            "Globe Swift",
            "Grumman G-21 Goose",
            "Grumman G-44 Widgeon",
            "Grumman G-73 Mallard",
            "Grumman G-73T Turbo Mallard",
            "Grumman HU-16B Albatross",
            "Grumman S2/C1",
            "Grumman Tiger",
            "Grumman Turbo Goose",
            "Gulfstream Twin Commander 690B (Carenado)",
            "Hawker 850XP",
            "Hawker Siddeley HS-748",
            "Helio Super Courier H-295/U-10b",
            "Howard DGA-15",
            "Howard Aero 500",
            "Hughes 269",
            "Hughes/McDonnell Douglas MD500E",
            "Ilyushin Il-14",
            "Ilyushin Il-18D",
            "Junkers Ju-52",
            "Junkers W33 EW Flight",
            "Junkers W33/34",
            "Kazan Helicopter Plant Mi-17-1V-GA",
            "Lake Renegade",
            "Lancair Legacy",
            "Lancair Legacy IV-P",
            "Lear 45",
            "Learjet 24B",
            "Learjet 24B - Tip Tanks",
            "Learjet 35A",
            "LearJet LJ25D",
            "Let L 410 UVP-E",
            "Let L 410 UVP-T",
            "Liberty XL2",
            "Lockheed C-130 (Capt Sim)",
            "Lockheed C-130 (Generic)",
            "Lockheed Constellation",
            "Lockheed L049 (A2A)",
            "Lockheed L10A Electra",
            "Lockheed L10E Amelia Special",
            "Lockheed Lodestar",
            "Lockheed P-3C (L-188)",
            "Lockheed Vega",
            "Luscombe 8A",
            "Martin 404",
            "Maule M-7",
            "McDonnell Douglas DC-10-30F",
            "Messerschmitt Bf 108 B",
            "Meyers 200D",
            "Mil Mi-2",
            "Mitsubishi MU-2B",
            "Mooney M20 Bravo",
            "Mooney M20 Juliet",
            "Morane-Saulnier MS-760",
            "NAMC YS-11",
            "New Standard D25A",
            "Noorduyn Norseman",
            "North American B-25",
            "North American P-51D Mustang",
            "North American T-28 Trojan",
            "North American T-39 Sabreliner",
            "North American T-6G Texan",
            "Pacific Aerospace 750XL",
            "Piaggio 166 Albatross",
            "Piaggio 180 Avanti",
            "Piaggio P-149D",
            "Pilatus PC-12",
            "Pilatus PC-6 Porter",
            "Piper J-3 Cub",
            "Piper PA-12 Super Cruiser RTW",
            "Piper PA-18 Super Cub",
            "Piper PA-20 Pacer",
            "Piper PA-22 Super Pacer",
            "Piper PA-22 Tri-Pacer",
            "Piper PA-23 Apache",
            "Piper PA-23 Aztec",
            "Piper PA-24 Comanche",
            "Piper PA-24 Comanche (A2A)",
            "Piper PA-28 Archer",
            "Piper PA-28 Arrow",
            "Piper PA-28 Cherokee 180",
            "Piper PA-28 Dakota",
            "Piper PA-28 Warrior",
            "Piper PA-30 Twin Comanche",
            "Piper PA-31 Navajo",
            "Piper PA-31T Cheyenne II",
            "Piper PA-31T1 Cheyenne I/IA",
            "Piper PA-31T2 Cheyenne IIXL",
            "Piper PA-32 Cherokee Six/ Saratoga",
            "Piper PA-32 Saratoga TC",
            "Piper PA-34 Seneca",
            "Piper PA-38 Tomahawk",
            "Piper PA-42-1000 Cheyenne 400",
            "Piper PA-44 Seminole",
            "Piper PA-46 Meridian",
            "Piper PA-60 Aerostar",
            "PZL Wilga",
            "Quest Kodiak",
            "Rans S-7 Courier",
            "Raytheon Beechjet / Hawker",
            "Raytheon Premier1",
            "Republic Seabee",
            "Robin DR400",
            "Robin HR200",
            "Robin/Apex DR221",
            "Robinson R22",
            "Robinson R44",
            "Robinson R66 Turbine",
            "Rockwell Commander 114",
            "Rockwell Twin Commander 690B",
            "Ryan L-17 Navion",
            "Saab 2000",
            "Saab 340B",
            "SAAB Scandia 90",
            "Scottish Aviation Twin Pioneer",
            "Shorts SD3-60",
            "Shorts Skyvan",
            "SIAI-Marchetti SF260",
            "SIAI-Marchetti SM.1019A",
            "Sikorsky S-43",
            "Sikorsky S-55",
            "Sikorsky S-76",
            "Sikorsky UH-60 Blackhawk",
            "Socata TB-10 Tobago",
            "Socata TB21GT Trinidad",
            "Socata TBM 700",
            "Socata TBM 850",
            "Spartan 7W Executive",
            "Stinson 108",
            "Stinson L-5B Sentinel",
            "Stinson Reliant",
            "Supermarine Spitfire",
            "Supermarine Walrus MK 1",
            "Tecnam P2006T",
            "Tecnam P92 Echo",
            "Tupolev Tu-124",
            "Vans RV-7/7A",
            "Vickers Viscount",
            "Waco Classic YMF",
            "Westland Seaking",
            "Yakovlev Yak-12A",
            "Yakovlev Yak-18T",
            "Yakovlev Yak-40",
            "Zenair CH 801",
            "Zepplin NT",
            "Zlin Z-43",
        };
    }

    /*
    public enum AircraftMakeModelEnum
    {
        Aermacchi_Lockheed_AL_60,
        Aero_Design_AC500C,
        Aero_Design_AC680S,
        Aero_Vodochody_L_39,
        Aeronca_Champion,
        Agusta_A109,
        Agusta_Westland_AW139,
        Airbus_A320,
        Airbus_A321,
        Airbus_H145,
        Airbus_Helicopters_H145,
        Aircreation_582SL,
        Airspeed_AS_57_Ambassador,
        Alenia_C_27J_Spartan,
        Alenia_C_27J_Spartan_IRIS,
        American_Champion_Scout,
        Antonov_An_14,
        Antonov_AN_2,
        Antonov_An_24,
        Antonov_An_26_Curl,
        Antonov_An_28,
        Antonov_An_32,
        ATR_42_500,
        ATR_72_500,
        Auster_J_1_Autocrat,
        Australia_GAF_N22_Nomad,
        Aviat_A_1_Husky,
        Avro_Anson_MK_1,
        BAC_Jet_Provost_T5,
        BAe_146_100_Avro_RJ70,
        BAe_Jetstream_32,
        BAe_Jetstream_41,
        Basler_BT_67,
        Beagle_B_206_Basset,
        Beechcraft_17,
        Beechcraft_18,
        Beechcraft_1900C,
        Beechcraft_1900C_Freighter,
        Beechcraft_1900D,
        Beechcraft_Baron_58,
        Beechcraft_Baron_58___tip_tanks_Dreamfleet,
        Beechcraft_Bonanza_A36,
        Beechcraft_Bonanza_F33,
        Beechcraft_Bonanza_V35,
        Beechcraft_Debonair,
        Beechcraft_Duchess_76,
        Beechcraft_Duke_B60,
        Beechcraft_King_Air_200,
        Beechcraft_King_Air_300,
        Beechcraft_King_Air_350,
        Beechcraft_King_Air_C90,
        Beechcraft_Queen_Air,
        Beechcraft_Queen_Air_80S,
        Beechcraft_Royal_Turbine_Duke_B60,
        Beechcraft_T_34_Mentor,
        Beechcraft_Twin_Bonanza_50,
        Bell_205A_1_UH_1C,
        Bell_206B,
        Bell_206L_RTW_N3911Z,
        Bell_212,
        Bell_407,
        Bell_407_Nemeth,
        Bell_412,
        Bell_429,
        Bell_430,
        Bell_430_RTW_N430Q,
        Bell_47G_2,
        Bell_UH_1H_Huey,
        Bellanca_260,
        Beriev_BE_103,
        Boeing_221A_Monomail,
        Boeing_247D,
        Boeing_377,
        Boeing_727_100_200,
        Boeing_737_800,
        Boeing_747_400,
        Boeing_B_17G,
        Boeing_Stearman,
        Boeing_Vertol_CH_46D_Sea_Knight_BV107,
        Boeing_Vertol_CH_47_Chinook,
        Bombardier_Challenger_300,
        Bombardier_CL_415,
        Bombardier_CRJ_200ER,
        Bombardier_CRJ700_ER,
        Bombardier_Dash_8_Q400,
        Bombardier_Lear_60,
        Bristol_Britannia_300,
        Bristol_Mark_32_Superfreighter,
        Britten_Norman_BN_2A_Mk3_3_Trislander,
        Britten_Norman_BN_2B_Islander,
        Bucker_Jungmann_131,
        CASA_CN235,
        Cessna_152_Aerobat,
        Cessna_162_Skycatcher,
        Cessna_172_Skyhawk,
        Cessna_177_Cardinal,
        Cessna_177RG_Cardinal,
        Cessna_182_Skylane,
        Cessna_185_Skywagon,
        Cessna_195,
        Cessna_206_Stationair,
        Cessna_207_Stationair_8,
        Cessna_208_Caravan,
        Cessna_210_Centurion,
        Cessna_310,
        Cessna_337_Skymaster,
        Cessna_340A,
        Cessna_404_Titan,
        Cessna_414A_Chancellor,
        Cessna_421_Golden_Eagle,
        Cessna_441_Conquest_II,
        Cessna_Citation_CJ1,
        Cessna_Citation_II,
        Cessna_Citation_X,
        Cessna_L_19_O_1_Birddog,
        Cessna_Mustang,
        Cessna_Soloy_Mk1_MkII_U206_Turbo,
        Cessna_T_50_Bobcat,
        Cessna_T303_Crusader,
        Cessna_Reims_F_406_Caravan_II,
        Cirrus_SR20,
        Cirrus_SR22_G2,
        Cirrus_Vision_SF50,
        Columbia_400,
        Commander_112,
        Commander_115,
        Consolidated_C_87_Liberator_Express,
        Consolidated_PBY5_Catalina,
        Convair_340_440,
        Convair_580,
        Curtiss_C46,
        Curtiss_Robertson_Robin_J_1,
        Dassault_Falcon_50,
        Dassault_Falcon_7X,
        DeHavilland_Dash_7,
        DeHavilland_Dash_8_100_200,
        DeHavilland_Dash_8_Q300,
        DeHavilland_DH_89_Dragon_Rapide,
        DeHavilland_DH_82_Tiger_Moth,
        DeHavilland_DH104_Dove,
        DeHavilland_DH114_Heron,
        DeHavilland_DH80A_Puss_Moth,
        DeHavilland_DHC_1_Chipmunk,
        DeHavilland_DHC_2_Beaver,
        DeHavilland_DHC_2_Turbo_Beaver,
        DeHavilland_DHC_3_Otter,
        DeHavilland_DHC_3_T_Turbo_Otter,
        DeHavilland_DHC_3T_Turbo_Otter_Milviz,
        DeHavilland_DHC_4_Caribou,
        DeHavilland_DHC_5_Buffalo,
        DeHavilland_DHC_6_300_Twin_Otter_Aerosoft_Extended,
        DeHavilland_DHC_6_Twin_Otter,
        Diamond_DA20_Katana,
        Diamond_DA40D_DiamondStar,
        Diamond_DA42_Twin_Star,
        Diamond_DA62,
        Dornier_228,
        Dornier_328,
        Dornier_Do_27_A4,
        Dornier_Do_27_B1,
        Dornier_Do_28_A_B,
        Douglas_A_26,
        Douglas_C117D,
        Douglas_DC_2,
        Douglas_DC_2_FSX,
        Douglas_DC_3,
        Douglas_DC_4,
        Douglas_DC_6,
        Douglas_DC_6B,
        Douglas_DC_6B_PMDG,
        Douglas_DC_7B,
        Douglas_DC_7C,
        Douglas_DC_8_10_40,
        Eclipse_500,
        Embraer_110,
        Embraer_120,
        Embraer_ERJ_135LR,
        Embraer_ERJ_145LR,
        Embraer_Legacy_600,
        Embraer_Phenom_100,
        Embraer_Phenom_300,
        ERCO_Ercoupe_415_C,
        Eurocopter_AS_332_Super_Puma,
        Eurocopter_AS_350_Ecureuil,
        Eurocopter_AS365,
        Eurocopter_BK117,
        Eurocopter_Colibri_EC_120,
        Eurocopter_EC_135,
        Fairchild_24R,
        Fairchild_C119,
        Fairchild_C123,
        Fairchild_Metro_III,
        Fairchild_PT19_26_Cornell,
        Fokker_50_,
        Fokker_F27_500_Friendship,
        Ford_Tri_Motor,
        Found_Bush_Hawk,
        Gippsland_GA8_Airvan,
        Globe_Swift,
        Grumman_G_21_Goose,
        Grumman_G_44_Widgeon,
        Grumman_G_73_Mallard,
        Grumman_G_73T_Turbo_Mallard,
        Grumman_HU_16B_Albatross,
        Grumman_S2_C1,
        Grumman_Tiger,
        Grumman_Turbo_Goose,
        Gulfstream_Twin_Commander_690B_Carenado,
        Hawker_850XP,
        Hawker_Siddeley_HS_748,
        Helio_Super_Courier_H_295_U_10b,
        Howard_DGA_15,
        Howard_Aero_500,
        Hughes_269,
        Hughes_McDonnell_Douglas_MD500E,
        Ilyushin_Il_14,
        Ilyushin_Il_18D,
        Junkers_Ju_52,
        Junkers_W33_EW_Flight,
        Junkers_W33_34,
        Kazan_Helicopter_Plant_Mi_17_1V_GA,
        Lake_Renegade,
        Lancair_Legacy,
        Lancair_Legacy_IV_P,
        Lear_45,
        Learjet_24B,
        Learjet_24B___Tip_Tanks,
        Learjet_35A,
        LearJet_LJ25D,
        Let_L_410_UVP_E,
        Let_L_410_UVP_T,
        Liberty_XL2,
        Lockheed_C_130_Capt_Sim,
        Lockheed_C_130_Generic,
        Lockheed_Constellation,
        Lockheed_L049_A2A,
        Lockheed_L10A_Electra,
        Lockheed_L10E_Amelia_Special,
        Lockheed_Lodestar_,
        Lockheed_P_3C_L_188,
        Lockheed_Vega,
        Luscombe_8A,
        Martin_404,
        Maule_M_7,
        McDonnell_Douglas_DC_10_30F,
        Messerschmitt_Bf_108_B,
        Meyers_200D,
        Mil_Mi_2,
        Mitsubishi_MU_2B,
        Mooney_M20_Bravo,
        Mooney_M20_Juliet_,
        Morane_Saulnier_MS_760,
        NAMC_YS_11,
        New_Standard_D25A,
        Noorduyn_Norseman,
        North_American_B_25,
        North_American_P_51D_Mustang,
        North_American_T_28_Trojan,
        North_American_T_39_Sabreliner,
        North_American_T_6G_Texan,
        Pacific_Aerospace_750XL,
        Piaggio_166_Albatross,
        Piaggio_180_Avanti,
        Piaggio_P_149D,
        Pilatus_PC_12,
        Pilatus_PC_6_Porter,
        Piper_J_3_Cub,
        Piper_PA_12_Super_Cruiser_RTW,
        Piper_PA_18_Super_Cub,
        Piper_PA_20_Pacer,
        Piper_PA_22_Super_Pacer,
        Piper_PA_22_Tri_Pacer,
        Piper_PA_23_Apache,
        Piper_PA_23_Aztec,
        Piper_PA_24_Comanche,
        Piper_PA_24_Comanche_(A2A),
        Piper_PA_28_Archer,
        Piper_PA_28_Arrow,
        Piper_PA_28_Cherokee_180,
        Piper_PA_28_Dakota,
        Piper_PA_28_Warrior,
        Piper_PA_30_Twin_Comanche,
        Piper_PA_31_Navajo,
        Piper_PA_31T_Cheyenne_II,
        Piper_PA_31T1_Cheyenne_I_IA,
        Piper_PA_31T2_Cheyenne_IIXL,
        Piper_PA_32_Cherokee_Six__Saratoga,
        Piper_PA_32_Saratoga_TC,
        Piper_PA_34_Seneca,
        Piper_PA_38_Tomahawk,
        Piper_PA_42_1000_Cheyenne_400,
        Piper_PA_44_Seminole,
        Piper_PA_46_Meridian,
        Piper_PA_60_Aerostar,
        PZL_Wilga,
        Quest_Kodiak,
        Rans_S_7_Courier,
        Raytheon_Beechjet_Hawker,
        Raytheon_Premier1,
        Republic_Seabee,
        Robin_DR400,
        Robin_HR200,
        Robin_Apex_DR221,
        Robinson_R22,
        Robinson_R44,
        Robinson_R66_Turbine,
        Rockwell_Commander_114,
        Rockwell_Twin_Commander_690B,
        Ryan_L_17_Navion,
        Saab_2000,
        Saab_340B,
        SAAB_Scandia_90,
        Scottish_Aviation_Twin_Pioneer,
        Shorts_SD3_60,
        Shorts_Skyvan,
        SIAI_Marchetti_SF260,
        SIAI_Marchetti_SM_1019A,
        Sikorsky_S_43,
        Sikorsky_S_55,
        Sikorsky_S_76,
        Sikorsky_UH_60_Blackhawk,
        Socata_TB_10_Tobago,
        Socata_TB21GT_Trinidad,
        Socata_TBM_700,
        Socata_TBM_850,
        Spartan_7W_Executive,
        Stinson_108,
        Stinson_L_5B_Sentinel,
        Stinson_Reliant,
        Supermarine_Spitfire,
        Supermarine_Walrus_MK_1,
        Tecnam_P2006T,
        Tecnam_P92_Echo,
        Tupolev_Tu_124,
        Vans_RV_7_7A,
        Vickers_Viscount,
        Waco_Classic_YMF,
        Westland_Seaking,
        Yakovlev_Yak_12A,
        Yakovlev_Yak_18T,
        Yakovlev_Yak_40,
        Zenair_CH_801,
        Zepplin_NT,
        Zlin_Z_43,
    }

    */

    
}
